/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FrequencyMeter
#define HEADER_FrequencyMeter
/*
htop - FrequencyMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

This meter written by Jeremiah B. Lowe
*/

#include "Meter.h"

extern int CPUFrequencyMeter_attributes[];

extern MeterClass CPUFrequencyMeter_class;

#endif
