/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ProcCPUInfo
#define HEADER_ProcCPUInfo

#define NULL_STR "(null)"

#include "stdio.h"
#include "stdint.h"

struct CoreInfo {
	float freq_mhz;
	uint16_t physical_id;
	uint16_t logical_id;
};
void CoreInfo_print(struct CoreInfo* core);
void CoreInfo_init(struct CoreInfo* info);

struct CPUInfo {
	uint16_t logical_cores;
	uint16_t physical_cores;
	uint16_t coreInfo_len;
	uint32_t cache_kb;
	struct CoreInfo* coreInfo;
	char* vendor;
	char* model;
};
void CPUInfo_print(struct CPUInfo* cpu);
struct CPUInfo* CPUInfo_create();
void CPUInfo_destroy(struct CPUInfo* info);
void CPUInfo_setModel(struct CPUInfo* info, char* model);
void CPUInfo_setVendor(struct CPUInfo* info, char* vendor);
float CPUInfo_getAverageFrequencyMHz(struct CPUInfo* info);
uint8_t CPUInfo_readProcFile(struct CPUInfo* info, FILE* cpuinfo);

#endif
