/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ProcCPUInfo
#define HEADER_ProcCPUInfo

#define IS_WHITESPACE(c) (c < '!' || c > '~')

#include "stdint.h"

struct CoreInfo {
	float freq_mhz;
	uint16_t physical_id;
	uint16_t logical_id;
};
void CoreInfo_print(struct CoreInfo* core);
void CoreInfo_init(struct CoreInfo* info);
extern void CoreInfo_destroy(struct CoreInfo* info);

struct CPUInfo {
	uint16_t logical_cores;
	uint16_t physical_cores;
	uint16_t coreInfo_len;
	uint32_t cache_kb;
	struct CoreInfo* coreInfo;
	char* vendor;
	char* model;
};
void CPUInfo_print(struct CPUInfo* cpu);
struct CPUInfo* CPUInfo_create();
void CPUInfo_destroy(struct CPUInfo* info);
void CPUInfo_readProcFile(FILE* cpuinfo, struct CPUInfo* info);

char* strtrim(char* str);
void seperate_kv_pair(char** key_ptr, char** val_ptr, char* line, uint32_t len);
void handle_core_pair(struct CoreInfo* info, char* key, char* value);
char* duplicate_str(char* str);
uint8_t handle_cpu_pair(struct CPUInfo* info, char* key, char* value);

#endif
